### ISSUE TITLE
NameError: name 'extra' is not defined

### ISSUE THREAD

**Issue by tdayris** [snakemake/snakemake-wrapper-utils#2]
Hi,

Many thanks for these utils, I'm applying the changes right now in the snakemake-wrappers.

However, I get an NameError at lines [12](https://github.com/snakemake/snakemake-wrapper-utils/blob/b9d0b484625c257de778f68be1ef3e35b73cb8f5/snakemake_wrapper_utils/java.py#L12), and [21](https://github.com/snakemake/snakemake-wrapper-utils/blob/master/snakemake_wrapper_utils/java.py#L21).

I'll fork this repository, and release the correction as a PR today.

**Comment by dlaehnemann** [comment]
Closed by #3 . Thanks!
