### ISSUE TITLE
Add rest of extra options to `bcftools_opts`?

### ISSUE THREAD

**Issue by nikostr** [snakemake/snakemake-wrapper-utils#8]
Hey, would it make sense to add the rest of the extra params into `bcftools_opts`? Currently additional extras need to be parsed again in the wrapper.

**Comment by fgvieira** [comment]
Do you mean parsing more common parameters through `bcftools_opts`? What other params did you have in mind?

**Comment by dlaehnemann** [comment]
This issue has been inactive for quite a while and there have been substantial changes to the respective `bcftools.py`. So maybe, this has already been addressed. If not, feel free to reopen this issue or file a pull request with specific suggestions.
